# Question

We ask the question: If the states $\rho$ and $\sigma$ are close to each other $\Vert \rho - \sigma \Vert_1 \leq \epsilon$, does there exist a projector $\Pi$, such that $\Pi \rho \Pi \leq (1+g_1(\epsilon)) \sigma$ and $\text{tr}(\Pi \sigma) \geq 1- g_2(\epsilon)$ for some small functions $g_1(\epsilon)$ and $g_2(\epsilon)$?

In this notebook, we focus on the case where the projectors consist of the eigenvectors of $\sigma$. 

Package imports:

In [20]:
import numpy as np
import random as rnd

Define the functions as $g_1(\epsilon):= 10\epsilon^{1/4}$ and $g_2(\epsilon):= \epsilon^{1/4}$:

In [21]:
def g1(eps):
    return 10*np.power(eps,1/4)

def g2(eps):
    return np.power(eps,1/4)

Parameters for the problem:
- N: dimension of $\rho$ and $\sigma$
- eps_max: is the maximum possible $\epsilon$ in the problem statement, we calculate actual distance later

In [22]:
N=4
eps_max = 1e-10

### Construction of $\sigma$

We can assume WLOG that $\sigma$ is a diagonal matrix. We need to make sure that at least some eigenvalues of $\sigma$ are smaller than $g_2(\epsilon)$, otherwise we can prove that the statement is true.

num_small: represents number of eigenvalues smaller than $g_2(\epsilon)$

In [23]:
num_small= rnd.randint(1, N-1)
eig_sigma= []

# Select num_small numbers smaller than g2(eps_max) randomly
for i in range(num_small):
    eig_sigma.append(rnd.uniform(0, g2(eps_max)))

# Calculate the sum of all the small eigenvalues
sum_small = sum(eig_sigma)

# Ensure that the sum of the small eigenvalues does not exceed 1
if sum_small > 1: 
    target_sum_small = rnd.uniform(0,1)

    # Rescale the small eigenvalues so that their sum is 
    eig_sigma = list(map(
                    lambda x: x*target_sum_small/sum_small, 
                    eig_sigma
                    )
                )
    sum_small = target_sum_small

# Choose the rest of the eigenvalues
eig_sigma_large = []

for i in range(num_small, N): 
    eig_sigma_large.append(rnd.uniform(0,1))

sum_large = sum(eig_sigma_large)
target_sum_large = 1- sum_small

# Rescale them so that their sum is 1- sum_small
eig_sigma_large = list(map(
                    lambda x: x*target_sum_large/sum_large, 
                    eig_sigma_large
                    )
                )

eig_sigma.extend(eig_sigma_large)

# Put the eigenvalues constructed in a diagonal matrix to create sigma 
sigma = np.diag(eig_sigma)

[[2.95930174e-03 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.75737230e-03 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.21749253e-04 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.94461577e-01]]


### Sampling $\rho$

To sample $\rho$, we sample two PSD matrices with trace=1, $P$ and $Q$ randomly until the matrix 
$$\sigma + \frac{\epsilon}{2}P - \frac{\epsilon}{2}Q$$
is positive. We choose this positive matrix to be $\rho$. Clearly, this has trace=1 and $\Vert \rho - \sigma \Vert_1 \leq \epsilon_{\max}$. We calculate the actual distance and use it for computation.

In [ ]:
from numpy.random import default_rng
rng = default_rng()

